@extends('layouts.app')

@section('content')
<div class="py-4 sm:py-6">
    <div class="container-70">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
            <div>
                <h1 class="text-2xl sm:text-3xl font-bold text-gray-800 dark:text-gray-200">Tự động tạo yêu cầu</h1>
                <p class="text-gray-600 dark:text-gray-400 mt-2">Quản lý việc tạo tự động yêu cầu trả hàng và gửi hàng từ các cửa hàng</p>
            </div>
            <div class="flex flex-wrap gap-3">
                <button onclick="refreshStats()" class="inline-flex items-center px-4 py-2 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white text-sm font-medium rounded-lg transition-all duration-200 shadow-md hover:shadow-lg touch-target">
                    <i class="fas fa-sync-alt mr-2"></i>Làm mới
                </button>
                <a href="{{ route('notifications.index') }}" class="inline-flex items-center px-4 py-2 bg-gradient-to-r from-gray-600 to-gray-700 hover:from-gray-700 hover:to-gray-800 text-white text-sm font-medium rounded-lg transition-all duration-200 shadow-md hover:shadow-lg touch-target">
                    <i class="fas fa-bell mr-2"></i>Xem thông báo
                </a>
            </div>
        </div>        <!-- Stats Cards -->
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4 mb-8" id="statsContainer">
            <!-- General Stats -->
            <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-blue-100 text-blue-600 dark:bg-blue-800 dark:text-blue-200">
                        <i class="fas fa-robot text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600 dark:text-gray-400">Tổng tự động</p>
                        <p class="text-xl font-semibold text-gray-900 dark:text-gray-100" id="totalAutoGenerated">-</p>
                    </div>
                </div>
            </div>

            <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-green-100 text-green-600 dark:bg-green-800 dark:text-green-200">
                        <i class="fas fa-calendar-day text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600 dark:text-gray-400">Hôm nay</p>
                        <p class="text-xl font-semibold text-gray-900 dark:text-gray-100" id="todayGenerated">-</p>
                    </div>
                </div>
            </div>

            <!-- Return Request Stats -->
            <div class="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-red-100 text-red-600 dark:bg-red-800 dark:text-red-200">
                        <i class="fas fa-undo text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600">Trả hàng</p>
                        <p class="text-xl font-semibold text-gray-900" id="returnRequestsTotal">-</p>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-red-100 text-red-600">
                        <i class="fas fa-clock text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600">Trả hàng chờ</p>
                        <p class="text-xl font-semibold text-gray-900" id="returnRequestsPending">-</p>
                    </div>
                </div>
            </div>

            <!-- Shipment Request Stats -->
            <div class="bg-white rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-purple-100 text-purple-600">
                        <i class="fas fa-truck text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600">Gửi hàng</p>
                        <p class="text-xl font-semibold text-gray-900" id="shipmentRequestsTotal">-</p>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-lg shadow p-4">
                <div class="flex items-center">
                    <div class="p-2 rounded-full bg-purple-100 text-purple-600">
                        <i class="fas fa-hourglass-half text-lg"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-xs font-medium text-gray-600">Gửi hàng chờ</p>
                        <p class="text-xl font-semibold text-gray-900" id="shipmentRequestsPending">-</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Command Output -->
        @if(session('command_output'))
        <div class="bg-gray-900 text-green-400 p-4 rounded-lg mb-6 font-mono text-sm">
            <h3 class="text-white mb-2">Kết quả thực hiện:</h3>
            <pre class="whitespace-pre-wrap">{{ session('command_output') }}</pre>
        </div>
        @endif

        <!-- Success/Error Messages -->
        @if(session('success'))
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-6">
            {{ session('success') }}
        </div>
        @endif

        @if(session('error'))
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
            {{ session('error') }}
        </div>
        @endif        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <!-- Return Requests Section -->
            <div class="space-y-6">
                <h2 class="text-2xl font-bold text-gray-800 flex items-center">
                    <i class="fas fa-undo text-red-600 mr-3"></i>
                    Yêu cầu trả hàng
                </h2>
                
                <!-- Random Return Generation Card -->
                <div class="bg-white rounded-lg shadow-lg">
                    <div class="bg-gradient-to-r from-red-500 to-red-600 text-white p-6 rounded-t-lg">
                        <h3 class="text-xl font-semibold flex items-center">
                            <i class="fas fa-dice mr-3"></i>
                            Tạo yêu cầu trả hàng ngẫu nhiên
                        </h3>
                        <p class="mt-2 text-red-100">Tạo yêu cầu trả hàng ngẫu nhiên từ các cửa hàng</p>
                    </div>

                    <form action="{{ route('admin.auto-generation.random') }}" method="POST" class="p-6">
                        @csrf
                        
                        <div class="space-y-4">
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">
                                    Phần trăm cửa hàng tham gia (%)
                                </label>
                                <input type="number" name="percentage" value="30" min="1" max="100"
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">
                                <p class="text-xs text-gray-500 mt-1">Mặc định: 30% cửa hàng sẽ tạo yêu cầu</p>
                            </div>

                            <div class="grid grid-cols-2 gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số sản phẩm tối thiểu
                                    </label>
                                    <input type="number" name="min_products" value="1" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số sản phẩm tối đa
                                    </label>
                                    <input type="number" name="max_products" value="5" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">
                                </div>
                            </div>
                        </div>

                        <div class="mt-6">
                            <button type="submit" 
                                    class="w-full bg-red-500 hover:bg-red-600 text-white font-semibold py-3 px-4 rounded-lg transition duration-200">
                                <i class="fas fa-play mr-2"></i>
                                Tạo yêu cầu trả hàng ngẫu nhiên
                            </button>
                        </div>
                    </form>
                </div>

                <!-- Smart Return Generation Card -->
                <div class="bg-white rounded-lg shadow-lg">
                    <div class="bg-gradient-to-r from-orange-500 to-orange-600 text-white p-6 rounded-t-lg">
                        <h3 class="text-xl font-semibold flex items-center">
                            <i class="fas fa-brain mr-3"></i>
                            Tạo yêu cầu trả hàng thông minh
                        </h3>
                        <p class="mt-2 text-orange-100">Phân tích và tạo yêu cầu dựa trên tình trạng kho</p>
                    </div>

                    <form action="{{ route('admin.auto-generation.smart') }}" method="POST" class="p-6">
                        @csrf
                        
                        <div class="space-y-4">
                            <div class="flex items-center">
                                <input type="checkbox" name="dry_run" value="1" 
                                       class="h-4 w-4 text-orange-600 focus:ring-orange-500 border-gray-300 rounded">
                                <label class="ml-2 block text-sm text-gray-700">
                                    Chế độ xem trước (không tạo yêu cầu thực sự)
                                </label>
                            </div>

                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">
                                    Ngày tồn kho dư thừa tối thiểu
                                </label>
                                <input type="number" name="min_overstock_days" value="30" min="1"
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">
                                <p class="text-xs text-gray-500 mt-1">Sản phẩm tồn quá lâu sẽ được đề xuất trả về</p>
                            </div>
                        </div>

                        <div class="mt-6">
                            <button type="submit" 
                                    class="w-full bg-orange-500 hover:bg-orange-600 text-white font-semibold py-3 px-4 rounded-lg transition duration-200">
                                <i class="fas fa-cogs mr-2"></i>
                                Phân tích và tạo yêu cầu thông minh
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Shipment Requests Section -->
            <div class="space-y-6">
                <h2 class="text-2xl font-bold text-gray-800 flex items-center">
                    <i class="fas fa-truck text-purple-600 mr-3"></i>
                    Yêu cầu gửi hàng
                </h2>
                
                <!-- Random Shipment Generation Card -->
                <div class="bg-white rounded-lg shadow-lg">
                    <div class="bg-gradient-to-r from-purple-500 to-purple-600 text-white p-6 rounded-t-lg">
                        <h3 class="text-xl font-semibold flex items-center">
                            <i class="fas fa-dice mr-3"></i>
                            Tạo yêu cầu gửi hàng ngẫu nhiên
                        </h3>
                        <p class="mt-2 text-purple-100">Tạo yêu cầu gửi hàng ngẫu nhiên từ các cửa hàng</p>
                    </div>

                    <form action="{{ route('admin.auto-generation.random-shipment') }}" method="POST" class="p-6">
                        @csrf
                        
                        <div class="space-y-4">
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">
                                    Phần trăm cửa hàng tham gia (%)
                                </label>
                                <input type="number" name="percentage" value="25" min="1" max="100"
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500">
                                <p class="text-xs text-gray-500 mt-1">Mặc định: 25% cửa hàng sẽ tạo yêu cầu</p>
                            </div>

                            <div class="grid grid-cols-2 gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số sản phẩm tối thiểu
                                    </label>
                                    <input type="number" name="min_products" value="1" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500">
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số sản phẩm tối đa
                                    </label>
                                    <input type="number" name="max_products" value="5" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500">
                                </div>
                            </div>

                            <div class="grid grid-cols-2 gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số lượng tối thiểu
                                    </label>
                                    <input type="number" name="min_quantity" value="5" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500">
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-2">
                                        Số lượng tối đa
                                    </label>
                                    <input type="number" name="max_quantity" value="50" min="1"
                                           class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500">
                                </div>
                            </div>
                        </div>

                        <div class="mt-6">
                            <button type="submit" 
                                    class="w-full bg-purple-500 hover:bg-purple-600 text-white font-semibold py-3 px-4 rounded-lg transition duration-200">
                                <i class="fas fa-play mr-2"></i>
                                Tạo yêu cầu gửi hàng ngẫu nhiên
                            </button>
                        </div>
                    </form>
                </div>

                <!-- Smart Shipment Generation Card -->
                <div class="bg-white rounded-lg shadow-lg">
                    <div class="bg-gradient-to-r from-blue-500 to-blue-600 text-white p-6 rounded-t-lg">
                        <h3 class="text-xl font-semibold flex items-center">
                            <i class="fas fa-brain mr-3"></i>
                            Tạo yêu cầu gửi hàng thông minh
                        </h3>
                        <p class="mt-2 text-blue-100">Phân tích và tạo yêu cầu dựa trên nhu cầu thực tế</p>
                    </div>

                    <form action="{{ route('admin.auto-generation.smart-shipment') }}" method="POST" class="p-6">
                        @csrf
                        
                        <div class="space-y-4">
                            <div class="flex items-center">
                                <input type="checkbox" name="dry_run" value="1" 
                                       class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded">
                                <label class="ml-2 block text-sm text-gray-700">
                                    Chế độ xem trước (không tạo yêu cầu thực sự)
                                </label>
                            </div>

                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">
                                    Ngưỡng tồn kho thấp
                                </label>
                                <input type="number" name="low_stock_threshold" value="10" min="1"
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">
                                <p class="text-xs text-gray-500 mt-1">Sản phẩm có tồn kho dưới mức này sẽ được bổ sung</p>
                            </div>

                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">
                                    Hệ số dự đoán nhu cầu
                                </label>
                                <input type="number" step="0.1" name="demand_multiplier" value="2.0" min="0.1" max="10"
                                       class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">
                                <p class="text-xs text-gray-500 mt-1">Nhân với nhu cầu gần đây để dự đoán số lượng cần</p>
                            </div>
                        </div>

                        <div class="mt-6">
                            <button type="submit" 
                                    class="w-full bg-blue-500 hover:bg-blue-600 text-white font-semibold py-3 px-4 rounded-lg transition duration-200">
                                <i class="fas fa-cogs mr-2"></i>
                                Phân tích và tạo yêu cầu thông minh
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
                            <i class="fas fa-play mr-2"></i>Tạo yêu cầu ngẫu nhiên
                        </button>
                    </div>
                </form>
            </div>

            <!-- Smart Generation Card -->
            <div class="bg-white rounded-lg shadow-lg">
                <div class="bg-gradient-to-r from-green-500 to-green-600 text-white p-6 rounded-t-lg">
                    <h2 class="text-xl font-semibold flex items-center">
                        <i class="fas fa-brain mr-3"></i>
                        Tạo yêu cầu thông minh
                    </h2>
                    <p class="mt-2 text-green-100">Phân tích tình hình và tạo yêu cầu dựa trên dữ liệu</p>
                </div>

                <form action="{{ route('admin.auto-generation.smart') }}" method="POST" class="p-6">
                    @csrf
                    
                    <div class="space-y-4">
                        <div class="flex items-center">
                            <input type="checkbox" name="dry_run" value="1" id="dryRun"
                                   class="h-4 w-4 text-green-600 focus:ring-green-500 border-gray-300 rounded">
                            <label for="dryRun" class="ml-2 text-sm font-medium text-gray-700">
                                Chế độ xem trước (không tạo yêu cầu thực)
                            </label>
                        </div>

                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Ngày tối thiểu tồn kho dư thừa
                            </label>
                            <input type="number" name="min_overstock_days" value="30" min="1"
                                   class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">
                            <p class="text-xs text-gray-500 mt-1">Sản phẩm tồn kho dư thừa bao nhiêu ngày sẽ được đánh dấu</p>
                        </div>

                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-2">
                                Ngưỡng doanh thu thấp (0-1)
                            </label>
                            <input type="number" name="low_turnover_threshold" value="0.1" min="0" max="1" step="0.01"
                                   class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">
                            <p class="text-xs text-gray-500 mt-1">0.1 = sản phẩm có doanh thu dưới 10% sẽ được đánh dấu</p>
                        </div>

                        <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                            <div class="flex items-start">
                                <i class="fas fa-lightbulb text-yellow-500 mt-1 mr-3"></i>
                                <div class="text-sm text-yellow-800">
                                    <p class="font-medium">Phân tích thông minh sẽ:</p>
                                    <ul class="mt-1 list-disc list-inside space-y-1">
                                        <li>Phát hiện hàng tồn kho quá mức</li>
                                        <li>Tìm sản phẩm bán chậm</li>
                                        <li>Xác định hàng sắp hết hạn</li>
                                        <li>Đề xuất số lượng tối ưu</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mt-6">
                        <button type="submit" 
                                class="w-full bg-green-500 hover:bg-green-600 text-white font-semibold py-3 px-4 rounded-lg transition duration-200">
                            <i class="fas fa-search mr-2"></i>Phân tích và tạo yêu cầu
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Schedule Information -->
        <div class="mt-8 bg-white rounded-lg shadow-lg">
            <div class="bg-gradient-to-r from-purple-500 to-purple-600 text-white p-6 rounded-t-lg">
                <h2 class="text-xl font-semibold flex items-center">
                    <i class="fas fa-clock mr-3"></i>
                    Lịch tự động
                </h2>
                <p class="mt-2 text-purple-100">Hệ thống sẽ tự động chạy theo lịch đã thiết lập</p>
            </div>
            <div class="p-6">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <h3 class="font-semibold text-gray-800 mb-3">Tạo yêu cầu ngẫu nhiên</h3>
                        <ul class="space-y-2 text-sm text-gray-600">
                            <li class="flex items-center">
                                <i class="fas fa-sun text-yellow-500 mr-2"></i>
                                Hàng ngày lúc 9:00 sáng (30% cửa hàng)
                            </li>
                            <li class="flex items-center">
                                <i class="fas fa-clock text-blue-500 mr-2"></i>
                                Mỗi 4 giờ (10% cửa hàng)
                            </li>
                        </ul>
                    </div>
                    <div>
                        <h3 class="font-semibold text-gray-800 mb-3">Phân tích thông minh</h3>
                        <ul class="space-y-2 text-sm text-gray-600">
                            <li class="flex items-center">
                                <i class="fas fa-brain text-green-500 mr-2"></i>
                                2 lần/ngày: 8:00 và 16:00
                            </li>
                            <li class="flex items-center">
                                <i class="fas fa-chart-line text-purple-500 mr-2"></i>
                                Giờ làm việc: 6:00, 12:00, 18:00
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    refreshStats();
});

function refreshStats() {
    fetch('{{ route("admin.auto-generation.stats") }}')
        .then(response => response.json())
        .then(data => {
            // General stats
            document.getElementById('totalAutoGenerated').textContent = data.total_auto_generated || '0';
            document.getElementById('todayGenerated').textContent = data.today_generated || '0';
            
            // Return request stats
            document.getElementById('returnRequestsTotal').textContent = data.return_requests?.total || '0';
            document.getElementById('returnRequestsPending').textContent = data.return_requests?.pending || '0';
            
            // Shipment request stats
            document.getElementById('shipmentRequestsTotal').textContent = data.shipment_requests?.total || '0';
            document.getElementById('shipmentRequestsPending').textContent = data.shipment_requests?.pending || '0';
        })
        .catch(error => {
            console.error('Error fetching stats:', error);
        });
}

// Auto refresh stats every 30 seconds
setInterval(refreshStats, 30000);
</script>
@endpush
@endsection
